[versions]
agp = "8.4.0"
datastorePreferences = "1.1.1"
kotlin = "1.9.22"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"
lifecycle = "2.7.0"
nav_version = "2.7.7"
fragment_version = "1.7.0"
databindingRuntime = "8.4.0"
dagger = "2.51.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", name = "ui-tooling-preview"}
compose-material3 = { module = "androidx.compose.material3:material3" , name ="material3" }
activity-compose = {module = "androidx.activity:activity-compose", name = "activity-compose", version.ref="activity"}
viemodel-compose = {module = "androidx.lifecycle:lifecycle-viewmodel-compose", name ="lifecycle-viewmodel-compose", version.ref="lifecycle"}
viewmodel = {module = "androidx.lifecycle:lifecycle-viewmodel-ktx", name ="lifecycle-viewmodel-ktx", version.ref="lifecycle"}
compose-ui = {module = "androidx.compose.ui:ui-tooling", name ="ui-tooling"}
compose-runtime = {module ="androidx.compose.runtime:runtime", name="runtime"}
compose-graphics = {module = "androidx.compose.ui:ui-graphics", name ="ui-graphics"}
runtime-compose = {module = "androidx.lifecycle:lifecycle-runtime-compose", name ="lifecycle-runtime-compose", version.ref="lifecycle"}
constraintlayout-compose = {module = "androidx.constraintlayout:constraintlayout-compose", name="constraintlayout-compose", version = "1.0.1"}
navigation-fragment = {module = "androidx.navigation:navigation-fragment", name ="navigation-fragment", version.ref = "nav_version" }
navigation-ui = {module = "androidx.navigation:navigation-ui", name ="navigation-ui", version.ref = "nav_version"}
navigation-compose = {module = "androidx.navigation:navigation-compose", name ="navigation-compose", version.ref = "nav_version" }
framgent-navigation = {module ="androidx.fragment:fragment-ktx", name = "fragment-ktx", version.ref = "fragment_version"}
recyclerview = {module = "androidx.recyclerview:recyclerview", name ="recyclerview", version = "1.3.2"}
recyclerview-selection = {module = "androidx.recyclerview:recyclerview-selection", name = "recyclerview-selection", version = "1.1.0" }
androidx-databinding-runtime = { group = "androidx.databinding", name = "databinding-runtime", version.ref = "databindingRuntime" }
dagger = {group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
safeargsKotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "nav_version"}
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }


