package com.example.compose
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF68548E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEBDDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF230F46)

val md_theme_light_secondary = Color(0xFF68548E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEBDDFF)
val md_theme_light_onSecondaryContainer = Color(0xFF230F46)

val md_theme_light_tertiary = Color(0xFF8C4F27)

val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF321200)
val md_theme_light_onTertiaryContainer = Color(0xFF321200)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEF7FF)
val md_theme_light_onBackground = Color(0xFF1D1B20)
val md_theme_light_surface = Color(0xFFFEF2FF)
val md_theme_light_onSurface = Color(0xFF1D1B20)
val md_theme_light_surfaceVariant = Color(0xFFF9EEFF)
val md_theme_light_onSurfaceVariant = Color(0xFF19171C)
val md_theme_light_outline = Color(0xFF7A757F)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF7)
val md_theme_light_inverseSurface = Color(0xFFD2BCFD)
val md_theme_light_inversePrimary = Color(0xFFD2BCFD)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6B4FA2)
val md_theme_light_outlineVariant = Color(0xFFCBC4CF)
val md_theme_light_scrim = Color(0xFF000000)


val md_theme_dark_primary = Color(0xFFD2BCFD)
val md_theme_dark_onPrimary = Color(0xFF38265C)
val md_theme_dark_primaryContainer = Color(0xFF4F3D74)
val md_theme_dark_onPrimaryContainer = Color(0xFFEBDDFF)
val md_theme_dark_secondary = Color(0xFFD3BCFD)
val md_theme_dark_onSecondary = Color(0xFF38265C)
val md_theme_dark_secondaryContainer = Color(0xFF4F3D74)
val md_theme_dark_onSecondaryContainer = Color(0xFFEBDDFF)
val md_theme_dark_tertiary = Color(0xFFFFB68C)

val md_theme_dark_onTertiary = Color(0xFF532200)
val md_theme_dark_tertiaryContainer = Color(0xFF6F3812)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBC9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF151218)
val md_theme_dark_onBackground = Color(0xFFE7E0E8)
val md_theme_dark_surface = Color(0xFF280B42)
val md_theme_dark_onSurface = Color(0xFFE7E0E8)
val md_theme_dark_surfaceVariant = Color(0xFF412F54)
val md_theme_dark_onSurfaceVariant = Color(0xFFCBC4CF)
val md_theme_dark_outline = Color(0xFF948F99)
val md_theme_dark_inverseOnSurface = Color(0xFF322F35)
val md_theme_dark_inverseSurface = Color(0xFFE7E0E8)
val md_theme_dark_inversePrimary = Color(0xFF68548E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD3BBFF)
val md_theme_dark_outlineVariant = Color(0xFF49454E)
val md_theme_dark_scrim = Color(0xFF000000)

val md_theme_my_royal = Color(0xFFF3E6FD)



val seed = Color(0xFF59467F)
